const AUTH_CONFIG_JWT_EXPIRY_TIME = "365d";
const AUTH_CONFIG_JWT_SECRET = "U#a03NM3_rVQ!z!:st#k}Gg.PzmUy[l)w.kg6QDR:|t(pVYHOMyX8z:xT<%-3";

export {AUTH_CONFIG_JWT_SECRET, AUTH_CONFIG_JWT_EXPIRY_TIME}